export const styles = {
  container: "w-full h-screen bg-slate-900 relative overflow-hidden",
  canvas: "w-full h-full",
  overlay: "absolute top-0 left-0 right-0 p-4 pointer-events-none",
  header: "bg-slate-800/80 backdrop-blur-sm rounded-2xl p-4 shadow-xl pointer-events-auto",
  headerTop: "flex items-center justify-between mb-2",
  headerTitle: "flex items-center gap-2",
  title: "text-xl font-bold text-white",
  addButton: "bg-emerald-500 hover:bg-emerald-600 text-white p-2 rounded-xl transition-colors",
  stats: "flex gap-4 text-sm",
  stat: "flex items-center gap-2 text-gray-300",
  statValue: "font-mono",
  modal: "absolute inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 pointer-events-auto",
  modalContent: "bg-slate-800 rounded-2xl p-6 w-full max-w-md shadow-2xl",
  modalTitle: "text-xl font-bold text-white mb-4",
  formContainer: "space-y-4",
  label: "block text-sm font-medium text-gray-300 mb-1",
  input: "w-full bg-slate-700 text-white rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-emerald-500",
  buttonGroup: "flex gap-3",
  submitButton: "flex-1 bg-emerald-500 hover:bg-emerald-600 text-white font-medium py-3 rounded-xl transition-colors",
  cancelButton: "flex-1 bg-slate-700 hover:bg-slate-600 text-white font-medium py-3 rounded-xl transition-colors",
  instructions: "absolute bottom-4 left-4 right-4 pointer-events-none",
  instructionsBox: "bg-slate-800/80 backdrop-blur-sm rounded-xl p-3 text-center pointer-events-auto",
  instructionsText: "text-sm text-gray-300"
};